# Generated by Django 5.2.12 on 2026-05-30 01:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '__first__'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambios',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('total_devolucion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excedente_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago_excedente', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_credito', models.ForeignKey(blank=True, db_column='id_credito', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creditos.creditos')),
                ('id_vendedor', models.ForeignKey(blank=True, db_column='id_vendedor', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ventas')),
            ],
            options={
                'db_table': 'cambios',
            },
        ),
        migrations.CreateModel(
            name='CambioDetallesSalida',
            fields=[
                ('id_detalle_salida', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('id_cambio', models.ForeignKey(db_column='id_cambio', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_salida', to='Cambios.cambios')),
            ],
            options={
                'db_table': 'cambio_detalles_salida',
            },
        ),
        migrations.CreateModel(
            name='CambioDetallesEntrada',
            fields=[
                ('id_detalle_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_pactado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('id_cambio', models.ForeignKey(db_column='id_cambio', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entrada', to='Cambios.cambios')),
            ],
            options={
                'db_table': 'cambio_detalles_entrada',
            },
        ),
    ]
