# Generated by Django 5.2.12 on 2026-05-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoTalla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'producto_tallas',
                'managed': False,
            },
        ),
    ]
